import React from 'react'
import {Link} from 'react-router-dom';
import Nav from './Nav';
export default function Menu() {
    return (
        <div>
            <Nav />
            <h2 className='bg-[#28292d] text-white pt-40 sm:px-40 px-2 flex flex-col gap-3 mx-auto'>
                <p>In a restaurant, the menu is a list of food and beverages offered to customers and the prices. A menu may be à la carte – which presents a list of options from which customers choose – or table d'hôte, in which case a pre-established sequence of courses is offered. Menus may be printed on paper sheets provided to the diners, put on a large poster or display board inside the establishment, displayed outside the restaurant, or put on a digital screen. Since the late 1990s, some restaurants have put their menus online.</p>
                <p>Menus are also often a feature of very formal meals other than in restaurants, for example at weddings. In the 19th and 20th centuries printed menus were often used for society dinner-parties in homes; indeed this was their original use in Europe.</p>
                <p>Menus for private functions, pre-paid meals and the like do not have prices. In normal restaurants, there are two types of menus without prices that were mostly used until the 1970s and 1980s: the "blind menu" and the "women's menu". These menus contained all of the same items as the regular menu, except that the prices were not listed. The "blind menu" was distributed to guests at business meals where the hosts did not want the diners to see the prices, or to any type of dinner where the host felt that having the prices not listed would make the guests feel more comfortable ordering.</p>
                <p>As early as the mid-20th century, some restaurants have relied on "menu specialists" to design and print their menus.[6] Prior to the emergence of digital printing, these niche printing companies printed full-color menus on offset presses. The economics of full-color offset made it impractical to print short press runs. The solution was to print a "menu shell" with everything but the prices. The prices would later be printed on a less costly black-only press. In a typical order, the printer might produce 600 menu shells, then finish and laminate 150 menus with prices. When the restaurant needed to reorder, the printer would add prices and laminate some of the remaining shells.</p>
                <p>With the advent of digital presses, it became practical in the 1990s to print full-color menus affordably in short press runs, sometimes as few as 25 menus. Because of limits on sheet size, larger laminated menus were impractical for single-location independent restaurants to produce press runs of as few as 300 menus, but some restaurants may want to place far fewer menus into service. Some menu printers continue to use shells. The disadvantage for the restaurant is that it is unable to update anything but prices without creating a new shell.</p>
                <p>During the economic crisis in the 1970s, many restaurants found it costly to reprint the menu as inflation caused prices to increase. Economists noted this, and it has become part of economic theory, under the term "menu costs". In general, such "menu costs" may be incurred by a range of businesses, not just restaurants; for example, during a period of inflation, any company that prints catalogs or product price lists will have to reprint these items with new price figures.</p>
                <p>As a form of advertising, the prose found on printed menus is famous for the degree of its puffery. Menus frequently emphasize the processes used to prepare foods, call attention to exotic ingredients, and add French or other foreign language expressions to make the dishes appear sophisticated and exotic. "Menu language, with its hyphens, quotation marks, and random outbursts of foreign words, serves less to describe food than to manage your expectations"; restaurants are often "plopping in foreign words (80 percent of them French) like "spring mushroom civet", "pain of rabbit", "orange-jaggery gastrique".[8]</p>
                <p>Part of the function of menu prose is to impress customers with the notion that the dishes served at the restaurant require such skill, equipment, and exotic ingredients that the diners could not prepare similar foods at home.[8] In some cases, ordinary foods are made to sound more exciting by replacing everyday terms with their French equivalents. For example, instead of stating that a pork chop has a dollop of apple sauce, a high-end restaurant menu might say "Tenderloin of pork avec compote de Pommes." Although "avec compote de Pommes" translates directly as "with apple sauce", it sounds more exotic—and more worthy of an inflated price tag. Menus may use the culinary terms concassé to describe coarsely chopped vegetables, coulis to describe a purée of vegetables or fruit, or au jus, to describe meat served with its own natural gravy of pan drippings.</p>
               
            </h2>
        </div>
    )
}
